name: arch

on:
  push:
    branches:  
      - '**' 
  pull_request:
    branches:
       - '**' 

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt -y install make docker

    - name: Build arch developer docker container
      uses: docker/setup-buildx-action@v2
      run: make arch USER_NAME:=ci

